name: Test Access Secrets

on:
    workflow_dispatch:
    pull_request:
    issue_comment:
    pull_request_review:
    pull_request_review_comment:

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - name: Use secret
              run: echo "sdsdsdsd"
              env:
                TOKEN: ${{ secrets.IMPORTANT }}
