name: Test Access Secrets

on:
    workflow_dispatch:
    pull_request:

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - name: Use secret
              run: echo "sdsdsdsd2"
              env:
                TOKEN: ${{ secrets.IMPORTANT }}
